### ISSUE TITLE
WWW sivun highscore lista via python

### ISSUE THREAD

**Issue by AlexYliPaavalniemi** [22TIKO2D/GAME-PROJECT-GOTY-2023#40]
Pakollinen tuotos as per piilo pdf 🤷

**Comment by ghost** [comment]
Ymmärtääkseni tämä ei ollut täysin pakollinen; varsinkin jos se ei sovi peliin. Miten me edes pisteyttäisimme pelin? Tämän oli kai tarkoitus olla vain lisä duunia, jos jaksaa/ehtii tehdä.

**Comment by AlexYliPaavalniemi** [comment]
Jos tämä on näin niin sitten voidaan unohtaa. Se oltiin vaan pistetty samalle dialle pakollisten kielien kanssa, joten siitä päättelin sen olevan yhtä pakollinen.
